import React from 'react'
import Card from './components/Card'

const App = () => {

  const jobOpenings = [
  {
    id: 1,
    brandLogo: "https://media.wired.com/photos/5926ffe47034dc5f91bed4e8/3:2/w_2560%2Cc_limit/google-logo.jpg",
    companyName: "Google",
    datePosted: "2 days ago",
    jobRole: "Frontend Developer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$58/hr",
    location: "Bangalore, India",
  },
  {
    id: 2,
    brandLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/3840px-Microsoft_logo.svg.png",
    companyName: "Microsoft",
    datePosted: "5 days ago",
    jobRole: "React Developer",
    tag1: "Full Time",
    tag2: "Mid Level",
    pay: "$62/hr",
    location: "Hyderabad, India",
  },
  {
    id: 3,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVByitatwVy2dZAVZOj2VNNhuoWzNrRZbBOfORmn5nzg&s",
    companyName: "Apple",
    datePosted: "1 day ago",
    jobRole: "iOS Software Engineer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$78/hr",
    location: "Cupertino, USA",
  },
  {
    id: 4,
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Amazon-logo-meaning.jpg",
    companyName: "Amazon",
    datePosted: "4 days ago",
    jobRole: "Software Development Engineer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$55/hr",
    location: "Chennai, India",
  },
  {
    id: 5,
    brandLogo: "https://static.vecteezy.com/system/resources/thumbnails/004/201/564/small/meta-social-network-emblem-blue-stylish-letter-m-or-mobius-band-vector.jpg",
    companyName: "Meta",
    datePosted: "7 days ago",
    jobRole: "Frontend Engineer",
    tag1: "Full Time",
    tag2: "Mid Level",
    pay: "$72/hr",
    location: "Menlo Park, USA",
  },
  {
    id: 6,
    brandLogo: "https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/15844974/netflixlogo.0.0.1466448626.png?quality=90&strip=all&crop=1.2535702951444%2C0%2C97.492859409711%2C100&w=2400",
    companyName: "Netflix",
    datePosted: "10 days ago",
    jobRole: "UI Engineer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$85/hr",
    location: "Los Gatos, USA",
  },
  {
    id: 7,
    brandLogo: "https://images.seeklogo.com/logo-png/10/1/nvidia-logo-png_seeklogo-101614.png",
    companyName: "NVIDIA",
    datePosted: "3 days ago",
    jobRole: "Frontend Software Engineer",
    tag1: "Full Time",
    tag2: "Mid Level",
    pay: "$75/hr",
    location: "Pune, India",
  },
  {
    id: 8,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxDbGWS5_ZukEOuxyL-U1UE3JkQDIeTNaA6DfDim8Yy1oC6V1po5laBJI&s=10",
    companyName: "Adobe",
    datePosted: "8 days ago",
    jobRole: "React.js Developer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$60/hr",
    location: "Noida, India",
  },
  {
    id: 9,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBJU9zqrwCa9ZKxj8xb6R2wZDDkn67SMeOf9HPd8CfAujzDZJxhq5WJfN1&s=10",
    companyName: "Salesforce",
    datePosted: "6 days ago",
    jobRole: "Software Engineer",
    tag1: "Remote",
    tag2: "Mid Level",
    pay: "$68/hr",
    location: "Bangalore, India",
  },
  {
    id: 10,
    brandLogo: "https://images.seeklogo.com/logo-png/22/2/intel-logo-png_seeklogo-226413.png",
    companyName: "Intel",
    datePosted: "12 days ago",
    jobRole: "Java Developer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$52/hr",
    location: "Bangalore, India",
  },
  {
    id: 11,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT54KRS-5Mj-IYeavKKvuUKabpvUtJo5xrz_sjq8nXb5n9Zo9FtoInkmpLU&s=10",
    companyName: "Oracle",
    datePosted: "14 days ago",
    jobRole: "Cloud Engineer",
    tag1: "Hybrid",
    tag2: "Mid Level",
    pay: "$65/hr",
    location: "Austin, USA",
  },
  {
    id: 12,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfWwST4QkIIAcLkMLPWhvDsS_BnfK42zcPAQASiCZhWP1k4JxRD8bv0vg&s=10",
    companyName: "IBM",
    datePosted: "9 days ago",
    jobRole: "Backend Developer",
    tag1: "Part Time",
    tag2: "Junior Level",
    pay: "$45/hr",
    location: "Bangalore, India",
  },
  {
    id: 13,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiFF7m8_h3oGC-IkQEbX4SfSsOjdlWljQGTaVHmOkGP9w9gM84j-_CZaw&s=10",
    companyName: "Uber",
    datePosted: "11 days ago",
    jobRole: "Software Engineer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$82/hr",
    location: "San Francisco, USA",
  },
  {
    id: 14,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxdW8z4j8wRYw4Ue2DibGH6h8OQdobg99xbmktzvmp9UsctGc1bQyNw31T&s=10",
    companyName: "Airbnb",
    datePosted: "13 days ago",
    jobRole: "Frontend Engineer",
    tag1: "Remote",
    tag2: "Mid Level",
    pay: "$77/hr",
    location: "Remote",
  },
  {
    id: 15,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2u0n9nE48jBZzUSsxgLyIDQjlsszJUp0sqXMALySGyWuABVnXBdX3dw&s=10",
    companyName: "Spotify",
    datePosted: "15 days ago",
    jobRole: "React Native Developer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$74/hr",
    location: "Stockholm, Sweden",
  },
  {
    id: 16,
    brandLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1280px-LinkedIn_icon.svg.png",
    companyName: "LinkedIn",
    datePosted: "16 days ago",
    jobRole: "Frontend Software Engineer",
    tag1: "Hybrid",
    tag2: "Mid Level",
    pay: "$71/hr",
    location: "Sunnyvale, USA",
  },
  {
    id: 17,
    brandLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png",
    companyName: "Tesla",
    datePosted: "18 days ago",
    jobRole: "Full Stack Developer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$80/hr",
    location: "Austin, USA",
  },
  {
    id: 18,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa_xqH-opq-HCBtEDbf8tYRykvgOlcZmJkC7p_ckq7iw&s",
    companyName: "ByteDance",
    datePosted: "20 days ago",
    jobRole: "Frontend Engineer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$59/hr",
    location: "Singapore",
  },
  {
    id: 19,
    brandLogo: "https://images.icon-icons.com/2699/PNG/512/sap_logo_icon_170763.png",
    companyName: "SAP",
    datePosted: "21 days ago",
    jobRole: "Java Full Stack Developer",
    tag1: "Hybrid",
    tag2: "Mid Level",
    pay: "$63/hr",
    location: "Bangalore, India",
  },
  {
    id: 20,
    brandLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbvMW41X24vx6q7MogZuMBL-H1Jv3wJfY9MtJZt3wnjb4hEKfanzDAFvQ&s=10",
    companyName: "OpenAI",
    datePosted: "23 days ago",
    jobRole: "Frontend Engineer",
    tag1: "Remote",
    tag2: "Senior Level",
    pay: "$95/hr",
    location: "San Francisco, USA",
  },
];


return (
   <div className="parent">
   
{jobOpenings.map(function(elem,idx){

  return <div key={idx}>
    <Card company={elem.companyName} date={elem.datePosted} role={elem.jobRole} 
  rotation={elem.tag1} exps={elem.tag2} payment={elem.pay} location={elem.location} logo={elem.brandLogo}
  />
  </div>
})}
   </div>
  )
}

export default App
